# Generated by Django 4.2.13 on 2024-05-21 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_unit', models.TextField(null=True)),
                ('cur_nm', models.TextField(null=True)),
                ('ttb', models.TextField(null=True)),
                ('tts', models.TextField(null=True)),
            ],
        ),
    ]
